### ISSUE TITLE
SectionList doesn't appear to work

### ISSUE THREAD

**Issue by thungp** [cyrilmottier/ListViewTipsAndTricks#1]
on 6/9/2012 I did a clone of your repository.

I ran your app.
I tried to look at the SectionList example, but nothing gets displayed. 
It was running on an avd emulator 2.3.3

**Comment by rashiq** [comment]
same for me. The SectionList does not work.

**Comment by cyrilmottier** [comment]
This is not a bug. If you look at the code, you'll notice this example requires a device with multimedia (especially audio files). The device you are running on is obviously completely empty ...
